version: '3.8'

services:
  mysql-biblioteca:
    image: mysql:8.0
    container_name: mysql-biblioteca
    environment:
      MYSQL_ROOT_PASSWORD: JUANJOSE2021
      MYSQL_DATABASE: biblioteca_db
      MYSQL_USER: biblioteca_user
      MYSQL_PASSWORD: JUANJOSE2021
    ports:
      - "3306"
    volumes:
      - mysql_biblioteca_data:/var/lib/mysql

volumes:
  mysql_biblioteca_data:
